import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
import StyledComponentsRegistry from '../lib/AntdRegistry';
import { ConfigProvider } from 'antd';
import theme from '@/theme/themeConfig';


export const metadata: Metadata = {
    title: 'Invitation App',
    description: 'Generated by Elfan Nanda',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* <ConfigProvider theme={theme}> */}
                    <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
                {/* </ConfigProvider> */}
            </body>
        </html>
    )
}
